### PR TITLE
Added the Presentation file for the project

### PR DESCRIPTION
**Pull request by satyamksharma**
Added the presentation file for the project and its description

### CODE REVIEW

**Comment by satyamksharma** [comment]
merge plzz :|

**Review by SarthakSKumar — CHANGES_REQUESTED** [review]
Can you add the description at the top? Rather than having it at the bottom.

**Comment by SarthakSKumar** [comment]
Aslo, rename the PDF file to Notes_App_Presentation

**Comment by satyamksharma** [comment]
Done, check.

**Review by SarthakSKumar — CHANGES_REQUESTED** [review]
Push the description below the project title

**Review by SarthakSKumar — APPROVED** [review]

**Pull request merged**
